# The original, very inefficient code for computing the center of mass (COM) of a system of particles

In [2]:
# Challenge Code: Version 1 (Original)
import random

# Set up initial system or particles
x, y, z, m = [], [], [], []
for i in xrange(1000000): 
    x.append(random.uniform(0,100))
    y.append(random.uniform(0,100))
    z.append(random.uniform(0,100))
    m.append(random.uniform(1,10))

#Calculate the COM of the system (writing as a function makes it easier to time it!)
def f1_calc_com(x, y, z, m): 
    xmsum = 0
    for j in range(len(x)):
        xmsum = xmsum + x[j]*m[j]    
    xcm = xmsum/sum(m) 

    ymsum = 0
    for j in range(len(y)):
        ymsum = ymsum + y[j]*m[j]    
    ycm = ymsum/sum(m) 
    
    zmsum = 0
    for j in range(len(z)):
        zmsum = zmsum + z[j]*m[j]    
    zcm = zmsum/sum(m) 
    
    return xcm, ycm, zcm

In [3]:
%timeit f1_calc_com(x, y, z, m)

1 loop, best of 3: 840 ms per loop


# Now, write your optimized codes below.

In [11]:
# Challenge Code: Version 2 (Partially optimized using only Python lists)
import random

# Set up initial system or particles
x, y, z, m = [], [], [], []
for i in xrange(1000000): 
    x.append(random.uniform(0,100))
    y.append(random.uniform(0,100))
    z.append(random.uniform(0,100))
    m.append(random.uniform(1,10))

#Calculate the COM of the system (writing as a function makes it easier to time it!)
def f1_calc_com2(x, y, z, m): 
    xmsum = 0
    ymsum = 0
    zmsum = 0
    for j in range(len(x)):
        xmsum = xmsum + x[j]*m[j]
        ymsum = ymsum + y[j]*m[j] 
        zmsum = zmsum + z[j]*m[j] 
    xcm = xmsum/sum(m)
    ycm = ymsum/sum(m) 
    zcm = zmsum/sum(m) 
    
    return xcm, ycm, zcm

In [12]:
%timeit f1_calc_com2(x,y,z,m)

1 loop, best of 3: 304 ms per loop


In [7]:
# Challenge Code: Version 2 (Partially optimized using only Python lists)
import random

# Set up initial system or particles
x, y, z, m = [], [], [], []
x = [random.uniform(0,100) for i in xrange(1000000)]
y = [random.uniform(0,100) for i in xrange(1000000)]
z = [random.uniform(0,100) for i in xrange(1000000)]
m = [random.uniform(0,10) for i in xrange(1000000)]

#Calculate the COM of the system (writing as a function makes it easier to time it!)
def f1_calc_com2_Q1(x, y, z, m): 
    xmsum, ymsum, zmsum = 0, 0, 0
    msum_inv=1./sum(m)  # to use to speed up multi from div
    
    for j in range(len(x)):
        xmsum = xmsum + x[j]*m[j]
        ymsum = ymsum + y[j]*m[j] 
        zmsum = zmsum + z[j]*m[j] 
    xcm = xmsum*msum_inv
    ycm = ymsum*msum_inv
    zcm = zmsum*msum_inv
    
    return xcm, ycm, zcm

In [9]:
%timeit f1_calc_com2_Q1(x,y,z,m)

1 loop, best of 3: 298 ms per loop


In [11]:
# Challenge Code: Version 3 (Optimized using numpy arrays)
import random
import numpy as np

# Set up initial system or particles
x, y, z, m = [], [], [], []
for i in xrange(1000000): 
    x.append(random.uniform(0,100))
    y.append(random.uniform(0,100))
    z.append(random.uniform(0,100))
    m.append(random.uniform(1,10))

xnp = np.asarray(x)
ynp = np.asarray(y)
znp = np.asarray(z)
mnp = np.asarray(m)
#Calculate the COM of the system (writing as a function makes it easier to time it!)
def f1_calc_com3(x, y, z, m): 
    xcm=(xnp*mnp)/sum(m)
    ycm=(ynp*mnp)/sum(m)
    zcm=(znp*mnp)/sum(m)
    
    return xcm, ycm, zcm

In [12]:
%timeit f1_calc_com3(x,y,z,m)

10 loops, best of 3: 76 ms per loop


In [36]:
#Q3
import numpy as np
x = np.random.uniform(50,100,1000000)
y = np.random.uniform(30,90,1000000)
z = np.random.uniform(-50,50,1000000)
m = np.random.uniform(1,10,1000000) 

r= np.vstack((x,y,z))
r_use= np.swapaxes(r,0,1)
r_t=np.transpose(r)  # gives same setup as r_use but r_t is the correct answer

rcm = (r_use * m[:,np.newaxis]).sum(axis=0)/m.sum()

In [29]:
r

array([[ 60.48117811,  73.05615615,  97.63451598, ...,  92.14312487,
         77.95818507,  90.03634164],
       [ 40.92746865,  48.500198  ,  70.54405496, ...,  59.37170707,
         66.10437994,  43.38975042],
       [ 14.63799873,   3.62725269,   5.5535038 , ...,  25.75883871,
          8.35482526,  49.90237672]])

In [30]:
r_use

array([[ 60.48117811,  40.92746865,  14.63799873],
       [ 73.05615615,  48.500198  ,   3.62725269],
       [ 97.63451598,  70.54405496,   5.5535038 ],
       ..., 
       [ 92.14312487,  59.37170707,  25.75883871],
       [ 77.95818507,  66.10437994,   8.35482526],
       [ 90.03634164,  43.38975042,  49.90237672]])

In [31]:
r_t

array([[ 60.48117811,  40.92746865,  14.63799873],
       [ 73.05615615,  48.500198  ,   3.62725269],
       [ 97.63451598,  70.54405496,   5.5535038 ],
       ..., 
       [ 92.14312487,  59.37170707,  25.75883871],
       [ 77.95818507,  66.10437994,   8.35482526],
       [ 90.03634164,  43.38975042,  49.90237672]])

In [38]:
rcm = (r_use * m[:,np.newaxis]).sum(axis=0)/m.sum()

In [41]:
m

array([ 1.07781012,  2.22016889,  4.78197437, ...,  8.64769325,
        6.01348381,  3.07943764])

In [40]:
m[:,np.newaxis]  # flips it the other way

array([[ 1.07781012],
       [ 2.22016889],
       [ 4.78197437],
       ..., 
       [ 8.64769325],
       [ 6.01348381],
       [ 3.07943764]])

In [42]:
r_use * m[:,np.newaxis]

array([[  84.28902819,   59.87827667,    5.38901776],
       [ 205.43857809,  171.18839234,   -8.83558077],
       [ 280.74442436,  316.30154543, -176.49034786],
       ..., 
       [ 644.07642966,  456.82357439, -296.14546911],
       [ 322.16476614,  355.14835843,  -21.57497039],
       [ 159.39056668,  101.72021925,  100.989227  ]])

In [43]:
(r_use * m[:,np.newaxis]).sum(axis=0)  # axis = 0 is columns

array([  4.12373738e+08,   3.29873773e+08,  -9.86894822e+04])